//
//  BubbleStyleKit.swift
//  TwitSplit
//
//  Created by Luc Nguyen on 4/4/18.
//  Copyright © 2018 . All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class BubbleStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static let defaultColor: UIColor = UIColor(red: 0.000, green: 0.478, blue: 1.000, alpha: 1.000)
        static let errorColor: UIColor = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)
    }

    //// Colors

    public class var defaultColor: UIColor { return Cache.defaultColor }
    public class var errorColor: UIColor { return Cache.errorColor }

    //// Drawing Methods

    public class func drawBubbleCanvas(frame: CGRect = CGRect(x: 0, y: 0, width: 101, height: 34), color: UIColor = UIColor(red: 0.800, green: 0.320, blue: 0.320, alpha: 1.000), showQuoteSymbol: Bool = true) {

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath()
        rectanglePath.move(to: CGPoint(x: frame.minX + 23.71, y: frame.minY))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 33.07, y: frame.minY))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 15.77, y: frame.minY + 1.11), controlPoint1: CGPoint(x: frame.maxX - 23.33, y: frame.minY), controlPoint2: CGPoint(x: frame.maxX - 19.35, y: frame.minY))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 15.07, y: frame.minY + 1.27))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 4, y: frame.minY + 16.15), controlPoint1: CGPoint(x: frame.maxX - 8.42, y: frame.minY + 3.55), controlPoint2: CGPoint(x: frame.maxX - 4, y: frame.minY + 9.49))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 4, y: frame.minY + 0.50000 * frame.height), controlPoint1: CGPoint(x: frame.maxX - 4, y: frame.minY + 17), controlPoint2: CGPoint(x: frame.maxX - 4, y: frame.minY + 0.50000 * frame.height))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 4, y: frame.minY + 0.50000 * frame.height))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 4, y: frame.minY + 0.50000 * frame.height))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 4, y: frame.maxY - 16))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 15.07, y: frame.maxY - 1.27), controlPoint1: CGPoint(x: frame.maxX - 4, y: frame.maxY - 9.34), controlPoint2: CGPoint(x: frame.maxX - 8.42, y: frame.maxY - 3.55))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 31.28, y: frame.maxY), controlPoint1: CGPoint(x: frame.maxX - 19.35, y: frame.maxY), controlPoint2: CGPoint(x: frame.maxX - 23.33, y: frame.maxY))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 29.07, y: frame.maxY))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 11.77, y: frame.maxY - 1.11), controlPoint1: CGPoint(x: frame.minX + 19.33, y: frame.maxY), controlPoint2: CGPoint(x: frame.minX + 15.35, y: frame.maxY))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 11.07, y: frame.maxY - 1.27))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX, y: frame.maxY - 16.15), controlPoint1: CGPoint(x: frame.minX + 4.42, y: frame.maxY - 3.55), controlPoint2: CGPoint(x: frame.minX, y: frame.maxY - 9.49))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX, y: frame.minY + 0.50000 * frame.height), controlPoint1: CGPoint(x: frame.minX, y: frame.maxY - 17), controlPoint2: CGPoint(x: frame.minX, y: frame.minY + 0.50000 * frame.height))
        rectanglePath.addLine(to: CGPoint(x: frame.minX, y: frame.minY + 0.50000 * frame.height))
        rectanglePath.addLine(to: CGPoint(x: frame.minX, y: frame.minY + 0.50000 * frame.height))
        rectanglePath.addLine(to: CGPoint(x: frame.minX, y: frame.minY + 16.15))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 11.07, y: frame.minY + 1.27), controlPoint1: CGPoint(x: frame.minX, y: frame.minY + 9.49), controlPoint2: CGPoint(x: frame.minX + 4.42, y: frame.minY + 3.55))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 27.28, y: frame.minY), controlPoint1: CGPoint(x: frame.minX + 15.35, y: frame.minY), controlPoint2: CGPoint(x: frame.minX + 19.33, y: frame.minY))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 29.07, y: frame.minY))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 23.71, y: frame.minY))
        rectanglePath.close()
        color.setFill()
        rectanglePath.fill()


        if (showQuoteSymbol) {
            //// quoteCircle Drawing
            let quoteCirclePath = UIBezierPath()
            quoteCirclePath.move(to: CGPoint(x: frame.maxX - 23.99, y: frame.maxY - 32))
            quoteCirclePath.addCurve(to: CGPoint(x: frame.maxX - 6.12, y: frame.maxY - 16.47), controlPoint1: CGPoint(x: frame.maxX - 14.12, y: frame.maxY - 32), controlPoint2: CGPoint(x: frame.maxX - 6.12, y: frame.maxY - 25.57))
            quoteCirclePath.addCurve(to: CGPoint(x: frame.maxX - 6.16, y: frame.maxY - 8.94), controlPoint1: CGPoint(x: frame.maxX - 6.12, y: frame.maxY - 16.14), controlPoint2: CGPoint(x: frame.maxX - 6.16, y: frame.maxY - 8.94))
            quoteCirclePath.addCurve(to: CGPoint(x: frame.maxX, y: frame.maxY - 0.01), controlPoint1: CGPoint(x: frame.maxX - 6.16, y: frame.maxY - 4.99), controlPoint2: CGPoint(x: frame.maxX - 3.64, y: frame.maxY - 1.59))
            quoteCirclePath.addCurve(to: CGPoint(x: frame.maxX - 12.95, y: frame.maxY - 3.52), controlPoint1: CGPoint(x: frame.maxX - 4.75, y: frame.maxY - 0.09), controlPoint2: CGPoint(x: frame.maxX - 9.18, y: frame.maxY - 1.36))
            quoteCirclePath.addCurve(to: CGPoint(x: frame.maxX - 23.99, y: frame.maxY), controlPoint1: CGPoint(x: frame.maxX - 15.99, y: frame.maxY - 1.32), controlPoint2: CGPoint(x: frame.maxX - 19.82, y: frame.maxY))
            quoteCirclePath.addLine(to: CGPoint(x: frame.maxX - 23.83, y: frame.maxY))
            quoteCirclePath.addCurve(to: CGPoint(x: frame.maxX - 41.69, y: frame.maxY - 16.47), controlPoint1: CGPoint(x: frame.maxX - 33.7, y: frame.maxY), controlPoint2: CGPoint(x: frame.maxX - 41.69, y: frame.maxY - 7.37))
            quoteCirclePath.addCurve(to: CGPoint(x: frame.maxX - 23.83, y: frame.maxY - 32), controlPoint1: CGPoint(x: frame.maxX - 41.69, y: frame.maxY - 25.57), controlPoint2: CGPoint(x: frame.maxX - 33.7, y: frame.maxY - 32))
            quoteCirclePath.addLine(to: CGPoint(x: frame.maxX - 23.99, y: frame.maxY - 32))
            quoteCirclePath.close()
            color.setFill()
            quoteCirclePath.fill()
            color.setStroke()
            quoteCirclePath.lineWidth = 0
            quoteCirclePath.stroke()
        }
    }

    public class func drawRoundRect(frame: CGRect = CGRect(x: 0, y: 0, width: 52, height: 52)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!

        //// Rectangle Drawing
        context.saveGState()
        context.setAlpha(0.2)

        let rectanglePath = UIBezierPath()
        rectanglePath.move(to: CGPoint(x: frame.minX + 8.64, y: frame.minY + 0.5))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 8.64, y: frame.minY + 0.5))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 8.64, y: frame.minY + 0.5))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 4.19, y: frame.minY + 0.85), controlPoint1: CGPoint(x: frame.maxX - 5.83, y: frame.minY + 0.5), controlPoint2: CGPoint(x: frame.maxX - 5.13, y: frame.minY + 0.54))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 4.04, y: frame.minY + 0.89))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 0.9, y: frame.minY + 3.99), controlPoint1: CGPoint(x: frame.maxX - 2.55, y: frame.minY + 1.43), controlPoint2: CGPoint(x: frame.maxX - 1.43, y: frame.minY + 2.55))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 0.82, y: frame.minY + 4.28), controlPoint1: CGPoint(x: frame.maxX - 0.87, y: frame.minY + 4.1), controlPoint2: CGPoint(x: frame.maxX - 0.84, y: frame.minY + 4.19))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 0.5, y: frame.minY + 8.64), controlPoint1: CGPoint(x: frame.maxX - 0.54, y: frame.minY + 5.29), controlPoint2: CGPoint(x: frame.maxX - 0.5, y: frame.minY + 6))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 0.5, y: frame.maxY - 8.64))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 0.85, y: frame.maxY - 4.19), controlPoint1: CGPoint(x: frame.maxX - 0.5, y: frame.maxY - 5.83), controlPoint2: CGPoint(x: frame.maxX - 0.54, y: frame.maxY - 5.13))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 0.89, y: frame.maxY - 4.04))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 3.99, y: frame.maxY - 0.9), controlPoint1: CGPoint(x: frame.maxX - 1.43, y: frame.maxY - 2.55), controlPoint2: CGPoint(x: frame.maxX - 2.55, y: frame.maxY - 1.43))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 4.28, y: frame.maxY - 0.82), controlPoint1: CGPoint(x: frame.maxX - 4.1, y: frame.maxY - 0.87), controlPoint2: CGPoint(x: frame.maxX - 4.19, y: frame.maxY - 0.84))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 8.64, y: frame.maxY - 0.5), controlPoint1: CGPoint(x: frame.maxX - 5.29, y: frame.maxY - 0.54), controlPoint2: CGPoint(x: frame.maxX - 6, y: frame.maxY - 0.5))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 8.64, y: frame.maxY - 0.5))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 4.19, y: frame.maxY - 0.85), controlPoint1: CGPoint(x: frame.minX + 5.83, y: frame.maxY - 0.5), controlPoint2: CGPoint(x: frame.minX + 5.13, y: frame.maxY - 0.54))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 4.04, y: frame.maxY - 0.89))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 0.9, y: frame.maxY - 3.99), controlPoint1: CGPoint(x: frame.minX + 2.55, y: frame.maxY - 1.43), controlPoint2: CGPoint(x: frame.minX + 1.43, y: frame.maxY - 2.55))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 0.82, y: frame.maxY - 4.28), controlPoint1: CGPoint(x: frame.minX + 0.87, y: frame.maxY - 4.1), controlPoint2: CGPoint(x: frame.minX + 0.84, y: frame.maxY - 4.19))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 0.5, y: frame.maxY - 8.64), controlPoint1: CGPoint(x: frame.minX + 0.54, y: frame.maxY - 5.29), controlPoint2: CGPoint(x: frame.minX + 0.5, y: frame.maxY - 6))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 0.5, y: frame.minY + 8.64))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 0.85, y: frame.minY + 4.19), controlPoint1: CGPoint(x: frame.minX + 0.5, y: frame.minY + 5.83), controlPoint2: CGPoint(x: frame.minX + 0.54, y: frame.minY + 5.13))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 0.89, y: frame.minY + 4.04))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 3.99, y: frame.minY + 0.9), controlPoint1: CGPoint(x: frame.minX + 1.43, y: frame.minY + 2.55), controlPoint2: CGPoint(x: frame.minX + 2.55, y: frame.minY + 1.43))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 4.28, y: frame.minY + 0.82), controlPoint1: CGPoint(x: frame.minX + 4.1, y: frame.minY + 0.87), controlPoint2: CGPoint(x: frame.minX + 4.19, y: frame.minY + 0.84))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 8.64, y: frame.minY + 0.5), controlPoint1: CGPoint(x: frame.minX + 5.29, y: frame.minY + 0.54), controlPoint2: CGPoint(x: frame.minX + 6, y: frame.minY + 0.5))
        rectanglePath.close()
        rectanglePath.move(to: CGPoint(x: frame.minX + 8.64, y: frame.minY + 1.5))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 4.54, y: frame.minY + 1.78), controlPoint1: CGPoint(x: frame.minX + 6.1, y: frame.minY + 1.5), controlPoint2: CGPoint(x: frame.minX + 5.43, y: frame.minY + 1.54))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 4.31, y: frame.minY + 1.85), controlPoint1: CGPoint(x: frame.minX + 4.46, y: frame.minY + 1.8), controlPoint2: CGPoint(x: frame.minX + 4.39, y: frame.minY + 1.83))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 1.84, y: frame.minY + 4.33), controlPoint1: CGPoint(x: frame.minX + 3.17, y: frame.minY + 2.26), controlPoint2: CGPoint(x: frame.minX + 2.26, y: frame.minY + 3.17))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 1.81, y: frame.minY + 4.47))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 1.5, y: frame.minY + 8.64), controlPoint1: CGPoint(x: frame.minX + 1.54, y: frame.minY + 5.3), controlPoint2: CGPoint(x: frame.minX + 1.5, y: frame.minY + 5.96))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 1.5, y: frame.maxY - 8.64))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 1.78, y: frame.maxY - 4.54), controlPoint1: CGPoint(x: frame.minX + 1.5, y: frame.maxY - 6.1), controlPoint2: CGPoint(x: frame.minX + 1.54, y: frame.maxY - 5.43))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 1.85, y: frame.maxY - 4.31), controlPoint1: CGPoint(x: frame.minX + 1.8, y: frame.maxY - 4.46), controlPoint2: CGPoint(x: frame.minX + 1.83, y: frame.maxY - 4.39))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 4.33, y: frame.maxY - 1.84), controlPoint1: CGPoint(x: frame.minX + 2.26, y: frame.maxY - 3.17), controlPoint2: CGPoint(x: frame.minX + 3.17, y: frame.maxY - 2.26))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 4.47, y: frame.maxY - 1.81))
        rectanglePath.addCurve(to: CGPoint(x: frame.minX + 8.64, y: frame.maxY - 1.5), controlPoint1: CGPoint(x: frame.minX + 5.3, y: frame.maxY - 1.54), controlPoint2: CGPoint(x: frame.minX + 5.96, y: frame.maxY - 1.5))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 8.64, y: frame.maxY - 1.5))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 4.54, y: frame.maxY - 1.78), controlPoint1: CGPoint(x: frame.maxX - 6.1, y: frame.maxY - 1.5), controlPoint2: CGPoint(x: frame.maxX - 5.43, y: frame.maxY - 1.54))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 4.31, y: frame.maxY - 1.85), controlPoint1: CGPoint(x: frame.maxX - 4.46, y: frame.maxY - 1.8), controlPoint2: CGPoint(x: frame.maxX - 4.39, y: frame.maxY - 1.83))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 1.84, y: frame.maxY - 4.33), controlPoint1: CGPoint(x: frame.maxX - 3.17, y: frame.maxY - 2.26), controlPoint2: CGPoint(x: frame.maxX - 2.26, y: frame.maxY - 3.17))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 1.81, y: frame.maxY - 4.47))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 1.5, y: frame.maxY - 8.64), controlPoint1: CGPoint(x: frame.maxX - 1.54, y: frame.maxY - 5.3), controlPoint2: CGPoint(x: frame.maxX - 1.5, y: frame.maxY - 5.96))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 1.5, y: frame.minY + 8.64))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 1.78, y: frame.minY + 4.54), controlPoint1: CGPoint(x: frame.maxX - 1.5, y: frame.minY + 6.1), controlPoint2: CGPoint(x: frame.maxX - 1.54, y: frame.minY + 5.43))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 1.85, y: frame.minY + 4.31), controlPoint1: CGPoint(x: frame.maxX - 1.8, y: frame.minY + 4.46), controlPoint2: CGPoint(x: frame.maxX - 1.83, y: frame.minY + 4.39))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 4.33, y: frame.minY + 1.84), controlPoint1: CGPoint(x: frame.maxX - 2.26, y: frame.minY + 3.17), controlPoint2: CGPoint(x: frame.maxX - 3.17, y: frame.minY + 2.26))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 4.47, y: frame.minY + 1.81))
        rectanglePath.addCurve(to: CGPoint(x: frame.maxX - 8.64, y: frame.minY + 1.5), controlPoint1: CGPoint(x: frame.maxX - 5.3, y: frame.minY + 1.54), controlPoint2: CGPoint(x: frame.maxX - 5.96, y: frame.minY + 1.5))
        rectanglePath.addLine(to: CGPoint(x: frame.maxX - 8.64, y: frame.minY + 1.5))
        rectanglePath.addLine(to: CGPoint(x: frame.minX + 8.64, y: frame.minY + 1.5))
        rectanglePath.close()
        UIColor.darkGray.setFill()
        rectanglePath.fill()

        context.restoreGState()
    }

}
